#!/usr/bin/env python3
"""Generate Botany 2nd Year Chapters 1-5 SQL."""
import os
chapters = {
    1: ("Reproduction in Plants", "RP", [
        ("Asexual","Easy","Asexual reproduction produces","Genetically identical offspring (clones)","Genetically diverse","Hybrid","No offspring"),
        ("Vegetative","Easy","Vegetative propagation example is","Runner in grass, tuber in potato","Seeds","Spores only","Gametes"),
        ("Pollination","Easy","Pollination is transfer of pollen from","Anther to stigma","Root to shoot","Leaf to stem","Ovary to anther"),
        ("Self Poll","Easy","Self-pollination occurs within","Same flower or same plant","Different plants","Different species","Animals only"),
        ("Cross Poll","Medium","Cross-pollination occurs between","Different plants of same species","Same flower","Different species","Same plant"),
        ("Wind Poll","Easy","Anemophily is pollination by","Wind","Water","Insects","Birds"),
        ("Insect Poll","Easy","Entomophily is pollination by","Insects","Wind","Water","Birds"),
        ("Double Fert","Medium","Double fertilization involves","One sperm fuses egg, other fuses polar nuclei","Single fusion","Triple fusion only","No fusion"),
        ("Endosperm","Medium","Endosperm is formed by","Triple fusion (3n tissue)","Single fertilization","Pollination","Meiosis"),
        ("Embryo Sac","Hard","Mature embryo sac has","7 cells and 8 nuclei","8 cells","6 cells","4 cells"),
        ("Megaspore","Medium","Functional megaspore develops into","Female gametophyte (embryo sac)","Pollen grain","Seed","Fruit"),
        ("Microspore","Medium","Microspore develops into","Pollen grain (male gametophyte)","Embryo sac","Seed","Fruit"),
        ("Pollen Tube","Medium","Pollen tube grows through","Style to reach ovule","Root","Leaf","Stem"),
        ("Apomixis","Hard","Apomixis is formation of seeds","Without fertilization","With fertilization","By budding","By fragmentation"),
        ("Parthenocarpy","Medium","Parthenocarpy is development of fruit","Without fertilization (seedless)","With seeds","From root","From leaf"),
        ("Polyembryony","Hard","Polyembryony is occurrence of","More than one embryo in a seed","Single embryo","No embryo","Multiple seeds"),
        ("Pistil","Easy","Pistil consists of","Stigma, style, and ovary","Anther and filament","Petals","Sepals"),
        ("Stamen","Easy","Stamen consists of","Anther and filament","Stigma and style","Petals","Sepals"),
        ("Ovule","Medium","Ovule after fertilization becomes","Seed","Fruit","Pollen","Leaf"),
        ("Ovary Fruit","Easy","Ovary after fertilization becomes","Fruit","Seed","Root","Stem"),
        ("Outbreeding","Medium","Outbreeding devices prevent","Self-pollination","Cross-pollination","Vegetative growth","Asexual reproduction"),
        ("Pollen Viab","Medium","Pollen viability varies from","30 minutes to months depending on species","Always 1 day","Always 1 hour","Infinite"),
        ("Embryogeny","Hard","Embryogeny is the development of","Embryo from zygote","Pollen from microspore","Seed from ovule","Fruit from flower"),
        ("Chasmogamy","Medium","Chasmogamous flowers","Open and expose anthers and stigma","Never open","Are underground","Have no petals"),
        ("Cleistogamy","Medium","Cleistogamous flowers","Never open, self-pollination guaranteed","Always open","Cross-pollinate","Have no stamens"),
        ("Autogamy","Easy","Autogamy is","Self-pollination within same flower","Cross-pollination","Geitonogamy","Xenogamy"),
        ("Geitonogamy","Medium","Geitonogamy is pollination between","Different flowers of same plant","Different plants","Same flower","Animals"),
        ("Xenogamy","Medium","Xenogamy is","Cross-pollination between different plants","Self-pollination","Geitonogamy","Autogamy"),
        ("Seed Coat","Easy","Seed coat develops from","Integuments of ovule","Endosperm","Embryo","Pollen"),
        ("Perisperm","Hard","Perisperm is remnant of","Nucellus (persistent nucellus tissue)","Endosperm","Embryo","Seed coat"),
    ]),
    2: ("Principles of Inheritance and Variation", "PI", [
        ("Mendel","Easy","Father of genetics is","Gregor Johann Mendel","Darwin","Lamarck","Watson"),
        ("Dominance","Easy","Law of dominance states","One allele masks the other in heterozygote","Both express equally","Neither expresses","Random"),
        ("Segregation","Medium","Law of segregation states alleles","Separate during gamete formation","Stay together","Disappear","Multiply"),
        ("Independent","Medium","Law of independent assortment states genes on","Different chromosomes assort independently","Same chromosome","Always linked","Never separate"),
        ("Monohybrid","Easy","Monohybrid cross ratio in F2 is","3:1","1:1","9:3:3:1","1:2:1"),
        ("Dihybrid","Medium","Dihybrid cross ratio in F2 is","9:3:3:1","3:1","1:1","1:2:1"),
        ("Test Cross","Medium","Test cross is crossing with","Homozygous recessive","Homozygous dominant","Heterozygous","Any genotype"),
        ("Back Cross","Easy","Back cross is crossing F1 with","Either parent","Only dominant","Only recessive","F2"),
        ("Incomplete","Medium","Incomplete dominance gives F2 ratio","1:2:1 (e.g., pink snapdragon)","3:1","9:3:3:1","1:1"),
        ("Codominance","Medium","In codominance, both alleles","Express equally (e.g., AB blood group)","One masks other","Neither expresses","Blend"),
        ("Multiple All","Medium","Multiple alleles: ABO blood group has","3 alleles (IA, IB, i)","2 alleles","1 allele","4 alleles"),
        ("Pleiotropy","Hard","Pleiotropy: one gene affects","Multiple phenotypic traits","One trait","No traits","Only one organ"),
        ("Epistasis","Hard","Epistasis: one gene","Masks expression of another gene","Enhances","Has no effect","Duplicates"),
        ("Linkage","Medium","Linked genes are on","Same chromosome and tend to be inherited together","Different chromosomes","Different organisms","Same allele"),
        ("Crossing Over","Hard","Crossing over occurs during","Meiosis (pachytene of prophase I)","Mitosis","G1 phase","S phase"),
        ("Sex Linked","Medium","X-linked recessive traits like color blindness are more common in","Males (XY have only one X)","Females","Both equally","Neither"),
        ("Hemophilia","Medium","Hemophilia is","X-linked recessive bleeding disorder","Autosomal dominant","Y-linked","Autosomal recessive"),
        ("Color Blind","Easy","Red-green color blindness is","X-linked recessive","Autosomal dominant","Y-linked","Autosomal recessive"),
        ("Sex Determ","Easy","In humans, sex is determined by","XY system (XX=female, XY=male)","ZW system","XO system","Environment"),
        ("Pedigree","Medium","Pedigree analysis is used to","Trace inheritance pattern in families","Clone genes","Sequence DNA","Make vaccines"),
        ("Phenotype","Easy","Phenotype is","Observable characteristic","Genetic makeup","DNA sequence","Chromosome number"),
        ("Genotype","Easy","Genotype is","Genetic constitution of organism","Physical appearance","Phenotype","Behavior"),
        ("Homozygous","Easy","Homozygous means","Both alleles are same (AA or aa)","Different alleles","No alleles","Multiple alleles"),
        ("Heterozygous","Easy","Heterozygous means","Two different alleles (Aa)","Same alleles","No alleles","Three alleles"),
        ("Complementary","Hard","Complementary genes give F2 ratio","9:7","9:3:3:1","15:1","13:3"),
        ("Supplementary","Hard","Supplementary gene interaction ratio is","9:3:4","9:7","15:1","9:3:3:1"),
        ("Duplicate","Hard","Duplicate gene interaction gives ratio","15:1","9:7","9:3:4","13:3"),
        ("Polygenic","Medium","Polygenic inheritance: trait controlled by","Multiple genes with additive effect","Single gene","No genes","Cytoplasm"),
        ("Maternal","Hard","Maternal inheritance involves","Cytoplasmic/mitochondrial genes","Nuclear genes","Y-linked genes","Autosomal genes"),
        ("Chromosomal","Medium","Down syndrome is caused by","Trisomy 21 (extra chromosome 21)","Monosomy","Deletion","Duplication"),
    ]),
    3: ("Molecular Basis of Inheritance", "MB", [
        ("DNA Sugar","Easy","DNA contains sugar","Deoxyribose","Ribose","Glucose","Fructose"),
        ("RNA Sugar","Easy","RNA contains sugar","Ribose","Deoxyribose","Glucose","Sucrose"),
        ("Bases DNA","Easy","DNA bases are","A, T, G, C","A, U, G, C","Only A, T","Only G, C"),
        ("Bases RNA","Easy","RNA has uracil instead of","Thymine","Adenine","Guanine","Cytosine"),
        ("Chargaff","Medium","Chargaff rule: A=T and G=C means","Purines equal pyrimidines","All bases equal","A=G","T=C"),
        ("Double Helix","Easy","DNA double helix was proposed by","Watson and Crick (1953)","Mendel","Darwin","Griffith"),
        ("Replication","Medium","DNA replication is","Semiconservative","Conservative","Dispersive","Random"),
        ("Meselson","Hard","Meselson-Stahl experiment proved","Semiconservative replication using N15","Conservative","Dispersive","None"),
        ("Transcription","Medium","Transcription produces","mRNA from DNA template","DNA from RNA","Protein from DNA","DNA from protein"),
        ("Translation","Medium","Translation is synthesis of","Protein from mRNA at ribosome","mRNA from DNA","DNA from RNA","RNA from protein"),
        ("mRNA","Easy","mRNA carries genetic information from","Nucleus to ribosome","Ribosome to nucleus","Cell to cell","Organelle to organelle"),
        ("tRNA","Medium","tRNA carries","Amino acids to ribosome during translation","Genetic code","DNA","Lipids"),
        ("rRNA","Easy","rRNA is component of","Ribosomes","Nucleus","Mitochondria","Cell membrane"),
        ("Codon","Medium","Codon is sequence of","3 nucleotides on mRNA coding for 1 amino acid","2 nucleotides","4 nucleotides","1 nucleotide"),
        ("Anticodon","Medium","Anticodon is found on","tRNA (complementary to mRNA codon)","mRNA","rRNA","DNA"),
        ("Start Codon","Easy","Start codon AUG codes for","Methionine (initiator)","Stop","Alanine","Glycine"),
        ("Stop Codons","Easy","Stop codons are","UAA, UAG, UGA","AUG","AAA","GGG"),
        ("Genetic Code","Medium","Genetic code is","Universal, degenerate, non-overlapping, comma-less","Species-specific","Overlapping","Ambiguous"),
        ("Central Dogma","Medium","Central dogma: DNA -> RNA ->","Protein","DNA","Lipid","Carbohydrate"),
        ("Operon","Hard","Lac operon in E. coli is regulated by","Inducer (lactose) and repressor","Only promoter","Nothing","Temperature"),
        ("Structural","Medium","Structural genes in lac operon are","lacZ, lacY, lacA","Only lacZ","lacI","Promoter"),
        ("Repressor","Hard","Repressor protein binds to","Operator to block transcription","Promoter","Structural gene","Inducer"),
        ("HGP","Medium","Human Genome Project found humans have approximately","~20,000-25,000 genes","100,000 genes","1 million genes","1,000 genes"),
        ("DNA Fingerprint","Medium","DNA fingerprinting uses","Variable number tandem repeats (VNTRs/STRs)","Coding DNA","tRNA","rRNA"),
        ("Griffith","Medium","Griffith experiment demonstrated","Transformation in bacteria","Transduction","Conjugation","Translation"),
        ("Hershey Chase","Hard","Hershey-Chase proved DNA is genetic material using","Radioactive P32 and S35 with bacteriophage","Bacteria only","Mice","Plants"),
        ("Packaging","Hard","In eukaryotes, DNA is packaged with","Histone proteins into nucleosomes","Lipids","Carbohydrates","RNA"),
        ("Nucleosome","Hard","Nucleosome has DNA wrapped around","Octamer of histones (2 each of H2A,H2B,H3,H4)","4 histones","6 histones","10 histones"),
        ("Exon Intron","Medium","Exons are coding sequences, introns are","Non-coding sequences (removed by splicing)","Also coding","Proteins","Lipids"),
        ("Splicing","Hard","RNA splicing removes","Introns and joins exons to form mature mRNA","Exons","Both","Neither"),
    ]),
    4: ("Microbes in Human Welfare", "MW", [
        ("Curd","Easy","Curd formation from milk uses","Lactobacillus bacteria","Yeast","Virus","Fungus"),
        ("Fermentation","Easy","Alcoholic fermentation is done by","Yeast (Saccharomyces cerevisiae)","Bacteria","Virus","Algae"),
        ("Antibiotic","Easy","First antibiotic penicillin is obtained from","Penicillium notatum (fungus)","Bacteria","Virus","Algae"),
        ("Biogas","Medium","Biogas is produced by","Methanogenic bacteria (anaerobic)","Aerobic bacteria","Fungi","Algae"),
        ("Sewage","Medium","Primary treatment of sewage is","Physical (filtration, sedimentation)","Biological","Chemical","Nuclear"),
        ("Secondary","Medium","Secondary treatment of sewage uses","Aerobic microbes in aeration tanks","Chemicals","Filtration only","Heating"),
        ("BOD","Medium","BOD (Biochemical Oxygen Demand) indicates","Amount of organic matter in water","pH","Temperature","Salinity"),
        ("Biocontrol","Medium","Biocontrol uses","Living organisms to control pests","Chemicals","Radiation","Heat"),
        ("Bt Toxin","Hard","Bt toxin from Bacillus thuringiensis kills","Insect larvae (biological insecticide)","Plants","Humans","Fish"),
        ("Biofertilizer","Medium","Rhizobium is biofertilizer that fixes","Nitrogen in legume root nodules","Phosphorus","Potassium","Carbon"),
        ("Mycorrhiza","Medium","Mycorrhiza is symbiotic association of","Fungi with plant roots","Bacteria with roots","Algae with fungi","Virus with bacteria"),
        ("Yeast Bread","Easy","Yeast is used in bread making for","CO2 production (leavening)","Flavor only","Color","Preservation"),
        ("Vinegar","Easy","Vinegar (acetic acid) is produced by","Acetobacter bacteria","Yeast","Virus","Mold"),
        ("Citric Acid","Medium","Citric acid is produced by","Aspergillus niger (fungus)","Bacteria","Virus","Algae"),
        ("Swiss Cheese","Medium","Large holes in Swiss cheese are due to","CO2 by Propionibacterium shermanii","Yeast","Mold","Bacteria only"),
        ("Cyclosporin","Hard","Cyclosporin A (immunosuppressant) is from","Trichoderma polysporum (fungus)","Bacteria","Virus","Plant"),
        ("Statin","Hard","Statins (cholesterol-lowering) from","Monascus purpureus (yeast)","Bacteria","Plant","Animal"),
        ("SCP","Medium","Single cell protein (SCP) like Spirulina is used as","Food supplement (protein-rich)","Medicine","Fuel","Pesticide"),
        ("LAB","Easy","LAB (Lactic Acid Bacteria) convert milk sugar to","Lactic acid","Alcohol","Acetic acid","CO2"),
        ("Toddy","Easy","Toddy is made by fermenting","Palm sap using natural yeasts","Grapes","Barley","Rice"),
        ("Methanogens","Medium","Methanogens produce","Methane (biogas main component)","Oxygen","Nitrogen","CO2 only"),
        ("Gobar Gas","Easy","Gobar gas plant produces biogas from","Cattle dung (cow dung)","Coal","Petroleum","Wood"),
        ("BOD High","Medium","High BOD indicates water is","Highly polluted (more organic matter)","Clean","Pure","Safe"),
        ("Activated","Hard","Activated sludge in sewage treatment contains","Aerobic bacteria that digest organic matter","Chemicals","Sand","Gravel"),
        ("Flocs","Hard","Flocs in activated sludge are","Masses of bacteria + fungal filaments","Sand particles","Chemical crystals","Metal pieces"),
        ("Baculovirus","Hard","Baculovirus is used as","Biological control agent for insects","Medicine","Fertilizer","Food"),
        ("IPM","Medium","IPM stands for","Integrated Pest Management","Internal Pest Method","Insect Protection Mode","None"),
        ("Azotobacter","Medium","Azotobacter is free-living","Nitrogen-fixing bacterium","Phosphorus fixer","Potassium fixer","Carbon fixer"),
        ("Blue Green","Medium","Cyanobacteria (blue-green algae) fix","Atmospheric nitrogen in paddy fields","Phosphorus","Potassium","Sulfur"),
        ("Antibiotics","Easy","Antibiotics from microbes include","Penicillin, streptomycin, tetracycline","Only penicillin","Only aspirin","Only paracetamol"),
    ]),
    5: ("Biotechnology Principles and Processes", "BP", [
        ("Definition","Easy","Biotechnology uses","Living organisms or their products for human benefit","Only chemicals","Only physics","Only machines"),
        ("Restriction","Medium","Restriction enzymes are","Molecular scissors that cut DNA at specific sequences","DNA polymerase","Ligase","Helicase"),
        ("Ligase","Medium","DNA ligase is used to","Join DNA fragments","Cut DNA","Copy DNA","Read DNA"),
        ("Vector","Medium","Cloning vector is","DNA molecule that carries foreign DNA into host","Restriction enzyme","Ligase","Primer"),
        ("Plasmid","Easy","Plasmid is","Small circular DNA in bacteria (used as vector)","RNA","Protein","Lipid"),
        ("PCR","Medium","PCR (Polymerase Chain Reaction) amplifies","Specific DNA segment using Taq polymerase","RNA","Protein","Lipids"),
        ("Taq","Hard","Taq polymerase is from","Thermus aquaticus (thermostable)","E. coli","Yeast","Human"),
        ("Gel Electro","Medium","Gel electrophoresis separates DNA by","Size (smaller fragments move faster)","Color","Weight","Shape"),
        ("EcoRI","Medium","EcoRI is a restriction enzyme that recognizes","GAATTC sequence","AATTCC","GGCC","TTAA"),
        ("Sticky Ends","Medium","Sticky ends are","Single-stranded overhangs after restriction enzyme cut","Blunt ends","Closed loops","Circular DNA"),
        ("Transform","Medium","Transformation is uptake of","Foreign DNA by bacterial cell","Protein","RNA","Lipids"),
        ("Recombinant","Easy","Recombinant DNA contains DNA from","Two or more different sources","One source","No DNA","RNA only"),
        ("Competent","Hard","Competent cells are treated with","CaCl2 to take up DNA","HCl","NaOH","KCl"),
        ("Selectable","Medium","Selectable marker helps identify","Transformants (cells with recombinant DNA)","All cells","Dead cells","No cells"),
        ("Bioreactor","Medium","Bioreactor is used for","Large-scale production of biotechnology products","Small scale only","Sequencing","Cloning only"),
        ("Downstream","Hard","Downstream processing includes","Purification and quality control of product","Only fermentation","DNA extraction","Cloning"),
        ("Gene Gun","Medium","Gene gun (biolistics) shoots","DNA-coated gold/tungsten particles into cells","RNA","Protein","Chemicals"),
        ("Ti Plasmid","Hard","Ti plasmid of Agrobacterium is used for","Transferring genes to plants","Animal cloning","Bacteria only","Virus"),
        ("Ori","Medium","Origin of replication (ori) is needed for","Autonomous replication of vector in host","Cutting DNA","Translation","Transcription"),
        ("Reporter","Medium","Reporter gene (e.g., GFP, lacZ) helps","Detect presence of insert in vector","Cut DNA","Join DNA","Replicate"),
        ("Insertional","Hard","Insertional inactivation: foreign DNA inserted into","Antibiotic resistance gene (inactivates it)","Promoter","Origin","Terminator"),
        ("Blue White","Hard","Blue-white screening uses","lacZ gene disruption (white = recombinant)","Color of bacteria","Size","Shape"),
        ("cDNA","Hard","cDNA is made from","mRNA using reverse transcriptase","DNA directly","Protein","Lipids"),
        ("Probe","Hard","DNA probe is used to","Detect specific DNA sequence by hybridization","Cut DNA","Join DNA","Amplify"),
        ("Southern","Hard","Southern blotting detects","Specific DNA sequences","RNA","Protein","Lipids"),
        ("Northern","Hard","Northern blotting detects","Specific RNA sequences","DNA","Protein","Lipids"),
        ("Western","Hard","Western blotting detects","Specific proteins","DNA","RNA","Lipids"),
        ("Microinject","Medium","Microinjection introduces DNA directly into","Animal cell nucleus","Plant cell","Bacteria","Virus"),
        ("Electropor","Hard","Electroporation uses","Electric pulses to make cell membrane permeable","Heat","Cold","Pressure"),
        ("Palindrome","Medium","Restriction enzymes recognize","Palindromic DNA sequences","Any sequence","Only AT","Only GC"),
    ]),
}

output_lines = ["-- TS Inter 2nd Year | BOTANY | ALL CHAPTERS | public_question_repository", "SET NAMES utf8mb4;"]
for ch_num, (ch_name, prefix, questions) in chapters.items():
    output_lines.append(f"\n-- ============ CHAPTER {ch_num}: {ch_name.upper()} (30 Qs) ============")
    output_lines.append("INSERT INTO public_question_repository (custom_id,course_tags,subject,chapter,topic,difficulty,is_pyq,pyq_year,text,option_a,option_b,option_c,option_d,correct_answer,explanation,image_path,marks,created_at) VALUES")
    rows = []
    for i, q in enumerate(questions, 1):
        topic, diff, text, a, b, c, d = q[0], q[1], q[2], q[3], q[4], q[5], q[6]
        expl = q[7] if len(q) > 7 else "Standard concept."
        cid = f"12-BOT-{prefix}-{i:04d}"
        pyq = "1,2019" if i == 5 else ("1,2020" if i == 10 else ("1,2021" if i == 15 else "0,NULL"))
        def esc(s): return s.replace("'", "''")
        row = f"('{cid}','TS-Inter-2,BiPC,JEE','Botany','{esc(ch_name)}','{esc(topic)}','{diff}',{pyq},'{esc(text)}','{esc(a)}','{esc(b)}','{esc(c)}','{esc(d)}','A','{esc(expl)}',NULL,1,NOW())"
        rows.append(row)
    output_lines.append(",\n".join(rows) + ";")

base = r"c:\exam-app\backend\scripts"
with open(os.path.join(base, "ts_inter2_botany_all.sql"), "w", encoding="utf-8") as f:
    f.write("\n".join(output_lines))
print(f"Written Botany Ch 1-5: {sum(len(v[2]) for v in chapters.values())} questions")
