"""Syllabus vocabulary for Splice, pre-split into fragments.

This is the only hand-authored content in the games feature. Everything else
generates itself from a date seed; this list is written once and only touched
when you want more variety.

Each entry is `(WORD, [fragments], category)` where the fragments concatenate
back to the word exactly and each is at least two letters. Splits are authored
by hand rather than computed: an automatic hyphenator produces fragments like
"S" and "TRIANG" that make the puzzle feel arbitrary, whereas a human split
lands on morphemes ("PHOTO" + "SYN" + "THESIS") that a student can actually
reason about. `test_games.py` asserts every split still reassembles.

Words may repeat across bands — the two lists are drawn from independently.
Sharing a fragment between two words is fine and needs no fixing: the draw
guard in `splice.py` simply never puts those two in the same puzzle.

At four words a day, a list of this size keeps a given word from reappearing
for roughly two and a half months.
"""

# Classes 6-7: shorter words, mostly two fragments.
BAND_6_7 = [
    ("MAGNET", ["MAG", "NET"], "Physics"),
    ("FRICTION", ["FRIC", "TION"], "Physics"),
    ("GRAVITY", ["GRA", "VITY"], "Physics"),
    ("CIRCUIT", ["CIR", "CUIT"], "Physics"),
    ("CURRENT", ["CUR", "RENT"], "Physics"),
    ("VOLTAGE", ["VOLT", "AGE"], "Physics"),
    ("ENERGY", ["ENER", "GY"], "Physics"),
    ("PRESSURE", ["PRES", "SURE"], "Physics"),
    ("DENSITY", ["DEN", "SITY"], "Physics"),
    ("BALANCE", ["BAL", "ANCE"], "Physics"),
    ("SUNLIGHT", ["SUN", "LIGHT"], "Physics"),
    ("TELESCOPE", ["TELE", "SCOPE"], "Physics"),
    ("MICROSCOPE", ["MICRO", "SCOPE"], "Physics"),
    ("VOLUME", ["VOL", "UME"], "Maths"),
    ("FRACTION", ["FRACT", "ION"], "Maths"),
    ("DECIMAL", ["DEC", "IMAL"], "Maths"),
    ("TRIANGLE", ["TRI", "ANGLE"], "Maths"),
    ("PERIMETER", ["PERI", "METER"], "Maths"),
    ("SYMMETRY", ["SYM", "METRY"], "Maths"),
    ("INTEGER", ["INTE", "GER"], "Maths"),
    ("ALGEBRA", ["ALGE", "BRA"], "Maths"),
    ("DIAMETER", ["DIAM", "ETER"], "Maths"),
    ("RADIUS", ["RAD", "IUS"], "Maths"),
    ("QUADRANT", ["QUAD", "RANT"], "Maths"),
    ("OXYGEN", ["OXYG", "EN"], "Chemistry"),
    ("HYDROGEN", ["HYDRO", "GEN"], "Chemistry"),
    ("NITROGEN", ["NIT", "ROGEN"], "Chemistry"),
    ("MIXTURE", ["MIXT", "URE"], "Chemistry"),
    ("SOLUTION", ["SO", "LUTION"], "Chemistry"),
    ("CRYSTAL", ["CRYS", "TAL"], "Chemistry"),
    ("MINERAL", ["MINE", "RAL"], "Chemistry"),
    ("SKELETON", ["SKEL", "ETON"], "Biology"),
    ("NUTRIENT", ["NUT", "RIENT"], "Biology"),
    ("VITAMIN", ["VITA", "MIN"], "Biology"),
    ("BACTERIA", ["BAC", "TERIA"], "Biology"),
    ("HABITAT", ["HABI", "TAT"], "Biology"),
    ("MAMMAL", ["MAM", "MAL"], "Biology"),
    ("REPTILE", ["REP", "TILE"], "Biology"),
    ("INSECT", ["IN", "SECT"], "Biology"),
    ("FLOWER", ["FLOW", "ER"], "Biology"),
    ("SEEDLING", ["SEED", "LING"], "Biology"),
    ("CHLOROPHYLL", ["CHLORO", "PHYLL"], "Biology"),
    ("DIGESTION", ["DIGES", "TION"], "Biology"),
    ("BREATHING", ["BREATH", "ING"], "Biology"),
    ("MUSCLE", ["MUS", "CLE"], "Biology"),
    ("NEURON", ["NEU", "RON"], "Biology"),
    ("FOSSIL", ["FOS", "SIL"], "Geography"),
    ("FOREST", ["FOR", "EST"], "Geography"),
    ("DESERT", ["DES", "ERT"], "Geography"),
    ("GLACIER", ["GLA", "CIER"], "Geography"),
    ("VOLCANO", ["VOLC", "ANO"], "Geography"),
    ("MONSOON", ["MON", "SOON"], "Geography"),
    ("EQUATOR", ["EQUA", "TOR"], "Geography"),
    ("WEATHER", ["WEA", "THER"], "Geography"),
    ("CLIMATE", ["CLI", "MATE"], "Geography"),
    ("RAINFALL", ["RAIN", "FALL"], "Geography"),
    ("EARTHQUAKE", ["EARTH", "QUAKE"], "Geography"),
    ("CONTINENT", ["CONTI", "NENT"], "Geography"),
    ("PENINSULA", ["PENIN", "SULA"], "Geography"),
    ("PLATEAU", ["PLA", "TEAU"], "Geography"),
    ("LATITUDE", ["LATI", "TUDE"], "Geography"),
    ("LONGITUDE", ["LONGI", "TUDE"], "Geography"),
    ("COMPASS", ["COM", "PASS"], "Geography"),
    ("PLANET", ["PLAN", "ET"], "Geography"),
    ("SATELLITE", ["SATEL", "LITE"], "Geography"),
    ("GALAXY", ["GAL", "AXY"], "Geography"),
    ("HISTORY", ["HIS", "TORY"], "History"),
    ("ANCIENT", ["ANCI", "ENT"], "History"),
    ("EMPIRE", ["EM", "PIRE"], "History"),
    ("CULTURE", ["CUL", "TURE"], "History"),
    ("HARVEST", ["HAR", "VEST"], "History"),
    ("TEXTILE", ["TEX", "TILE"], "History"),
    ("GRAMMAR", ["GRAM", "MAR"], "English"),
    ("ADJECTIVE", ["ADJEC", "TIVE"], "English"),
    ("PRONOUN", ["PRO", "NOUN"], "English"),
    ("SENTENCE", ["SEN", "TENCE"], "English"),
    ("PARAGRAPH", ["PARA", "GRAPH"], "English"),
    ("LIBRARY", ["LIB", "RARY"], "English"),
]

# Classes 8-10: longer words, more three-fragment splits.
BAND_8_10 = [
    ("VELOCITY", ["VELO", "CITY"], "Physics"),
    ("ACCELERATION", ["ACCEL", "ERATION"], "Physics"),
    ("MOMENTUM", ["MOMEN", "TUM"], "Physics"),
    ("INERTIA", ["INER", "TIA"], "Physics"),
    ("REFRACTION", ["REFRAC", "TION"], "Physics"),
    ("DISPERSION", ["DISPER", "SION"], "Physics"),
    ("AMPLITUDE", ["AMPLI", "TUDE"], "Physics"),
    ("FREQUENCY", ["FREQU", "ENCY"], "Physics"),
    ("WAVELENGTH", ["WAVE", "LENGTH"], "Physics"),
    ("RESISTANCE", ["RESIST", "ANCE"], "Physics"),
    ("CONDUCTOR", ["CONDUC", "TOR"], "Physics"),
    ("INSULATOR", ["INSUL", "ATOR"], "Physics"),
    ("TRANSFORMER", ["TRANS", "FORMER"], "Physics"),
    ("MAGNETISM", ["MAGNE", "TISM"], "Physics"),
    ("RADIOACTIVE", ["RADIO", "ACTIVE"], "Physics"),
    ("RESPIRATION", ["RESPIR", "ATION"], "Biology"),
    ("PHOTOSYNTHESIS", ["PHOTO", "SYN", "THESIS"], "Biology"),
    ("CHROMOSOME", ["CHROMO", "SOME"], "Biology"),
    ("HEREDITY", ["HERED", "ITY"], "Biology"),
    ("GENETICS", ["GENE", "TICS"], "Biology"),
    ("EVOLUTION", ["EVOL", "UTION"], "Biology"),
    ("ECOSYSTEM", ["ECO", "SYSTEM"], "Biology"),
    ("BIODIVERSITY", ["BIO", "DIVER", "SITY"], "Biology"),
    ("HORMONE", ["HOR", "MONE"], "Biology"),
    ("ENZYME", ["EN", "ZYME"], "Biology"),
    ("PLASMA", ["PLAS", "MA"], "Biology"),
    ("NEPHRON", ["NEPH", "RON"], "Biology"),
    ("ALVEOLI", ["ALVE", "OLI"], "Biology"),
    ("ARTERY", ["ART", "ERY"], "Biology"),
    ("CAPILLARY", ["CAPIL", "LARY"], "Biology"),
    ("PATHOGEN", ["PATHO", "GEN"], "Biology"),
    ("IMMUNITY", ["IMMUN", "ITY"], "Biology"),
    ("ANTIBIOTIC", ["ANTI", "BIOTIC"], "Biology"),
    ("COMBUSTION", ["COMBUS", "TION"], "Chemistry"),
    ("ELECTROLYSIS", ["ELECTRO", "LYSIS"], "Chemistry"),
    ("CATALYST", ["CATA", "LYST"], "Chemistry"),
    ("MOLECULE", ["MOLE", "CULE"], "Chemistry"),
    ("COMPOUND", ["COM", "POUND"], "Chemistry"),
    ("ELEMENT", ["ELE", "MENT"], "Chemistry"),
    ("ISOTOPE", ["ISO", "TOPE"], "Chemistry"),
    ("VALENCY", ["VAL", "ENCY"], "Chemistry"),
    ("OXIDATION", ["OXID", "ATION"], "Chemistry"),
    ("ALKALI", ["ALK", "ALI"], "Chemistry"),
    ("POLYMER", ["POLY", "MER"], "Chemistry"),
    ("CORROSION", ["CORRO", "SION"], "Chemistry"),
    ("DISTILLATION", ["DISTIL", "LATION"], "Chemistry"),
    ("POLYNOMIAL", ["POLY", "NOMIAL"], "Maths"),
    ("QUADRATIC", ["QUAD", "RATIC"], "Maths"),
    ("COEFFICIENT", ["COEFFI", "CIENT"], "Maths"),
    ("HYPOTENUSE", ["HYPO", "TENUSE"], "Maths"),
    ("TRIGONOMETRY", ["TRIGONO", "METRY"], "Maths"),
    ("PROBABILITY", ["PROBA", "BILITY"], "Maths"),
    ("STATISTICS", ["STATIS", "TICS"], "Maths"),
    ("LOGARITHM", ["LOGA", "RITHM"], "Maths"),
    ("CIRCUMFERENCE", ["CIRCUM", "FERENCE"], "Maths"),
    ("PARALLELOGRAM", ["PARALLELO", "GRAM"], "Maths"),
    ("CONGRUENT", ["CONGRU", "ENT"], "Maths"),
    ("BISECTOR", ["BISEC", "TOR"], "Maths"),
    ("ATMOSPHERE", ["ATMO", "SPHERE"], "Geography"),
    ("LITHOSPHERE", ["LITHO", "SPHERE"], "Geography"),
    ("BIOSPHERE", ["BIO", "SPHERE"], "Geography"),
    ("SEDIMENTARY", ["SEDI", "MENTARY"], "Geography"),
    ("TECTONIC", ["TEC", "TONIC"], "Geography"),
    ("EROSION", ["ERO", "SION"], "Geography"),
    ("CYCLONE", ["CYC", "LONE"], "Geography"),
    ("TSUNAMI", ["TSU", "NAMI"], "Geography"),
    ("IRRIGATION", ["IRRIG", "ATION"], "Geography"),
    ("AGRICULTURE", ["AGRI", "CULTURE"], "Geography"),
    ("URBANISATION", ["URBAN", "ISATION"], "Geography"),
    ("INDUSTRIAL", ["INDUS", "TRIAL"], "Geography"),
    ("DEMOCRACY", ["DEMO", "CRACY"], "Civics"),
    ("CONSTITUTION", ["CONSTI", "TUTION"], "Civics"),
    ("PARLIAMENT", ["PARLIA", "MENT"], "Civics"),
    ("FEDERALISM", ["FEDER", "ALISM"], "Civics"),
    ("SECULARISM", ["SECUL", "ARISM"], "Civics"),
    ("JUDICIARY", ["JUDIC", "IARY"], "Civics"),
    ("LEGISLATURE", ["LEGIS", "LATURE"], "Civics"),
    ("NATIONALISM", ["NATION", "ALISM"], "History"),
    ("IMPERIALISM", ["IMPERI", "ALISM"], "History"),
    ("REVOLUTION", ["REVOL", "UTION"], "History"),
    ("METAPHOR", ["META", "PHOR"], "English"),
    ("NARRATIVE", ["NARRA", "TIVE"], "English"),
    ("VOCABULARY", ["VOCAB", "ULARY"], "English"),
    ("SYLLABLE", ["SYLLA", "BLE"], "English"),
    ("CONJUNCTION", ["CONJUNC", "TION"], "English"),
    ("PREPOSITION", ["PREPO", "SITION"], "English"),
    ("ALLITERATION", ["ALLITER", "ATION"], "English"),
    ("PERSONIFICATION", ["PERSONI", "FICATION"], "English"),
]

WORDLISTS = {
    '6-7': BAND_6_7,
    '8-10': BAND_8_10,
}
